# Generated by Django 2.2.5 on 2021-08-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210809_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='chech_out',
            new_name='check_out',
        ),
    ]
