# Generated by Django 2.2.5 on 2021-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210809_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amentities',
            new_name='amenities',
        ),
    ]
