# Generated by Django 2.2.5 on 2021-08-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_auto_20210810_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(upload_to="room_phtos"),
        ),
    ]
